"""
Seeds a large catalog of car brands and models into deals.db so the website's
search drop-downs cover as many cars as possible (European market focus).

Idempotent: safe to run any time, existing entries are kept.

Usage:
    python seed_catalog.py
"""

from database import SessionLocal
from crud import get_or_create_brand, get_or_create_vehicle_model
from catalog_variations import VARIATIONS

CATALOG = {
    "Audi": ["A1", "A2", "A3", "A3 8L", "A3 8P", "A3 8V", "A4", "A4 B5", "A4 B6", "A4 B7",
             "A4 B8", "A4 B9", "A5", "A6", "A6 C5", "A6 C6", "A6 C7", "A6 C8", "A7",
             "A8", "A8 D2", "A8 D3", "A8 D4", "80", "80 B4", "90", "100", "100 C4",
             "Q2", "Q3", "Q5", "Q7", "Q8", "Q8 e-tron", "TT", "TT Mk1", "TT Mk2",
             "TT Mk3", "R8", "S1", "S3", "S4", "S5", "S6", "S8", "SQ5", "RS3", "RS4",
             "RS6", "e-tron", "e-tron GT"],
    "BMW": ["1er", "1er (E81/E87)", "1er (E82/E88)", "1er (F20/F21)", "1er (F40)",
            "2er (F22)", "2er Gran Coupé", "3er", "3er (E30)", "3er (E36)",
            "3er (E46)", "3er (E90)", "3er (F30)", "3er (G20)", "4er (F32)",
            "4er (G22)", "5er", "5er (E34)", "5er (E39)", "5er (E60)", "5er (F10)",
            "5er (G30)", "6er", "6er (E63/E64)", "6er (F06)", "7er", "7er (E32)",
            "7er (E38)", "7er (E65)", "7er (F01)", "7er (G11)", "8er (E31)",
            "8er (G14)", "Z1", "Z3", "Z4", "Z4 (E89)", "Z4 (G29)", "X1", "X2", "X3",
            "X4", "X5", "X6", "X7", "i3", "i8", "M2", "M3", "M4", "M5", "M6", "X5 M",
            "iX", "i4"],
    "Mercedes-Benz": ["A-Klasse", "A-Klasse (W168)", "A-Klasse (W169)", "A-Klasse (W176)",
            "A-Klasse (W177)", "B-Klasse", "B-Klasse (T245)", "B-Klasse (W246)",
            "C-Klasse", "C-Klasse (W202)", "C-Klasse (W203)", "C-Klasse (W204)",
            "C-Klasse (W205)", "C-Klasse (W206)", "CLK", "CLS", "CLS (C218)",
            "CLS (C257)", "E-Klasse", "E-Klasse (W124)", "E-Klasse (W210)",
            "E-Klasse (W211)", "E-Klasse (W212)", "E-Klasse (W213)", "G-Klasse",
            "GL", "GLA", "GLB", "GLC", "GLE", "GLS", "ML", "M-Klasse", "S-Klasse",
            "S-Klasse (W140)", "S-Klasse (W220)", "S-Klasse (W221)", "S-Klasse (W222)",
            "S-Klasse (W223)", "SL", "SLK", "SLK (R170)", "Vito", "Viano", "Sprinter",
            "Citan", "CLA", "CLE", "EQA", "EQB", "EQC", "EQE", "EQS", "AMG GT", "190 (W201)"],
    "Volkswagen": ["Golf", "Golf 1", "Golf 2", "Golf 3", "Golf 4", "Golf 5", "Golf 6",
            "Golf 7", "Golf 8", "Passat", "Passat B3", "Passat B4", "Passat B5",
            "Passat B6", "Passat B7", "Passat B8", "Polo", "Polo 2", "Polo 3",
            "Polo 6N", "Polo 9N", "Polo 6R", "Polo AW", "Jetta", "Jetta III",
            "Jetta IV", "Jetta VI", "Jetta VII", "Arteon", "Tiguan", "Tiguan II",
            "T-Roc", "T-Cross", "Taigo", "Touran", "Touran II", "Sharan", "Sharan II",
            "Caddy", "Caddy III", "Caddy IV", "Multivan", "California", "Crafter",
            "Transporter (T4)", "Transporter (T5)", "Transporter (T6)", "Up!",
            "Beetle", "Beetle (New)", "Scirocco", "Scirocco III", "Corrado", "Golf Plus",
            "Golf Sportsvan", "Eos", "Phaeton", "Touareg", "Touareg I", "Touareg II",
            "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz", "Lupo", "Fox", "Bora",
            "Vento"],
    "Opel": ["Corsa", "Corsa B", "Corsa C", "Corsa D", "Corsa E", "Corsa F", "Astra",
            "Astra F", "Astra G", "Astra H", "Astra J", "Astra K", "Insignia",
            "Insignia A", "Insignia B", "Mokka", "Mokka X", "Mokka B", "Zafira",
            "Zafira A", "Zafira B", "Zafira C", "Vectra", "Vectra B", "Vectra C",
            "Meriva", "Meriva A", "Meriva B", "Adam", "Crossland", "Crossland X",
            "Grandland", "Grandland X", "Combo", "Combo C", "Combo D", "Movano",
            "Vivaro", "Vivaro B", "Vivaro C", "Kadett", "Kadett E", "Omega", "Omega A",
            "Omega B", "Cascada", "Carlton", "Tigra", "Tigra B", "Agila", "Antara",
            "Frontera", "Monterey", "Signum", "Speedster", "GT", "Calibra",
            "Ascona"],
    "Ford": ["Fiesta", "Fiesta IV", "Fiesta V", "Fiesta VI", "Fiesta VII", "Focus",
            "Focus I", "Focus II", "Focus III", "Focus IV", "Mondeo", "Mondeo I",
            "Mondeo II", "Mondeo III", "Mondeo IV", "Mondeo V", "Kuga", "Kuga I",
            "Kuga II", "Kuga III", "Puma", "Puma (2020)", "Galaxy", "S-Max", "C-Max",
            "Grand C-Max", "Transit", "Transit Custom", "Ka", "Ka II", "Escort",
            "Escort Mk5", "Capri", "Sierra", "Orion", "Granada", "Scorpio", "Cougar",
            "Probe", "Ranger", "Transit Connect", "Fusion", "Focus C-Max", "Mustang",
            "Mustang Mach-E", "Explorer", "Edge", "S-Max II"],
    "Renault": ["Clio", "Clio I", "Clio II", "Clio III", "Clio IV", "Clio V", "Mégane",
            "Megane I", "Megane II", "Megane III", "Megane IV", "Scenic", "Grand Scenic",
            "Scenic IV", "Laguna", "Laguna I", "Laguna II", "Laguna III", "Twingo",
            "Twingo II", "Twingo III", "Zoé", "Captur", "Captur II", "Kadjar", "Kangoo",
            "Kangoo II", "Kangoo III", "Espace", "Espace IV", "Espace V", "Trafic",
            "Trafic II", "Trafic III", "Master", "Master III", "Talisman", "Talisman I",
            "Modus", "Grand Modus", "Koleos", "Latitude", "Fluence", "Vel Satis",
            "Avantime", "Laguna Grandtour", "Arkana", "Austral", "Rafale", "R5",
            "R12", "R19", "R21", "R25", "SuperFive", "Express", "Kadogg", "Thalia",
            "Symbol", "4 (R4)", "Twingo GT"],
    "Peugeot": ["208", "208 I", "208 II", "308", "308 I", "308 II", "308 III", "2008",
            "2008 I", "2008 II", "3008", "3008 I", "3008 II", "5008", "5008 I",
            "5008 II", "508", "508 I", "508 II", "307", "407", "406", "405", "306",
            "106", "205", "206", "207", "309", "Partner", "Partner II", "Partner III",
            "Rifter", "Berlingo", "Boxer", "Boxer III", "Expert", "Expert III",
            "Traveller", "RCZ", "108", "107", "1007", "607", "605", "408", "e-208",
            "e-2008", "e-3008", "iOn"],
    "Citroën": ["C1", "C1 I", "C1 II", "C2", "C3", "C3 I", "C3 II", "C3 III", "C3 Aircross",
            "C4", "C4 I", "C4 II", "C4 III", "C4 Cactus", "C4 Picasso", "Grand C4 Picasso",
            "C5", "C5 I", "C5 II", "C5 Aircross", "C6", "C8", "Berlingo", "Berlingo II",
            "Berlingo III", "Saxo", "Xsara", "Picasso", "Xsara Picasso", "Jumpy",
            "Jumpy II", "Jumper", "Jumper II", "Dispatch", "Relay", "C3 Pluriel",
            "C35", "CX", "BX", "Xantia", "XM", "AX", "Visa", "2CV", "C-Crosser",
            "Grand C4 SpaceTourer", "SpaceTourer", "DS3", "DS4", "DS5", "C15", "C25"],
    "Fiat": ["500", "500 (2007)", "500L", "500X", "Panda", "Panda II", "Panda III",
            "Punto", "Punto 188", "Punto 199", "Punto Evo", "Grande Punto", "Tipo",
            "Tipo (2016)", "Bravo", "Bravo II", "Stilo", "Croma", "Multipla",
            "Doblo", "Doblo II", "Doblo III", "Fiorino", "Qubo", "Ducato", "Ducato III",
            "Uno", "Seicento", "Cinquecento", "126", "127", "128", "131", "132",
            "Tempra", "Coupé", "Barchetta", "Spider", "124 Spider", "Palio", "Siena",
            "Albea", "Idea", "Grande Panda"],
    "Alfa Romeo": ["Giulietta", "Giulia", "Stelvio", "147", "156", "159", "GT", "Spider",
            "Mito", "Brera", "4C", "Alfasud", "33", "145", "146", "GTV", "GTV6",
            "Sprint", "75", "90", "164", "166", "SZ", "RZ", "155", "Giulietta (Type 116)",
            "Giulia (Type 105)", "Tonale", "Junior"],
    "Lancia": ["Ypsilon", "Delta", "Delta III", "Thema", "Lybra", "Musa", "Dedra", "Prisma",
            "Beta", "Gamma", "Trevi", "Montecarlo", "Stratos", "Fulvia", "Kappa",
            "Zeta", "Phedra", "Y", "Y10"],
    "Seat": ["Ibiza", "Ibiza II", "Ibiza III", "Ibiza IV", "Ibiza V", "Leon", "Leon I",
            "Leon II", "Leon III", "Leon IV", "Toledo", "Toledo I", "Toledo II",
            "Toledo III", "Toledo IV", "Arona", "Ateca", "Alhambra", "Alhambra II",
            "Altea", "Altea XL", "Exeo", "Cordoba", "Inca", "Marbella", "Arosa",
            "Ronda", "Malaga", "Tarraco", "Mii", "Cupra Ateca", "Cupra León",
            "Cupra Formentor", "Cupra Born", "Cupra Tavascan"],
    "Škoda": ["Fabia", "Fabia I", "Fabia II", "Fabia III", "Fabia IV", "Octavia",
            "Octavia I", "Octavia II", "Octavia III", "Octavia IV", "Superb",
            "Superb I", "Superb II", "Superb III", "Superb IV", "Rapid", "Scala",
            "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Enyaq Coupe", "Yeti", "Roomster",
            "Felicia", "Favorit", "Estelle", "Citigo", "Octavia Scout", "Kodiaq II",
            "Elroq"],
    "Volvo": ["S40", "S40 II", "S60", "S60 II", "S60 III", "S80", "S80 II", "V40",
            "V40 II", "V50", "V60", "V60 II", "V70", "V70 II", "V70 III", "V90",
            "XC40", "XC60", "XC60 II", "XC70", "XC90", "XC90 II", "240", "244",
            "245", "740", "760", "850", "940", "960", "S70", "C30", "C70",
            "S90", "S90 II", "C40", "Amazon", "P1800"],
    "Saab": ["9-3", "9-3 (1998)", "9-3 Sport Sedan", "9-5", "9-5 (2010)", "900",
             "9000", "9-2X", "9-4X", "Sonett", "Sonic", "9-X BioHybrid"],
    "Toyota": ["Yaris", "Yaris I", "Yaris II", "Yaris III", "Yaris IV", "Corolla",
            "Corolla E110", "Corolla E120", "Corolla E180", "Corolla E210", "Camry",
            "Auris", "Auris I", "Auris II", "Avensis", "Avensis II", "Avensis III",
            "RAV4", "RAV4 III", "RAV4 IV", "RAV4 V", "Land Cruiser", "Land Cruiser 70",
            "Hilux", "Hilux VII", "Supra", "Supra A80", "Supra A90", "GT86", "GR86",
            "Aygo", "Aygo II", "Aygo X", "Celica", "Celica T20", "Celica T23", "MR2",
            "MR2 W20", "Prius", "Prius II", "Prius III", "Prius IV", "C-HR",
            "Proace", "Proace Verso", "Yaris Cross", "Corolla Cross", "bZ4X", "RAV4 II",
            "RAV4 Prime", "Paseo", "Tercel", "Starlet", "Carina", "Carina E",
            "Carina II"],
    "Honda": ["Civic", "Civic EJ9", "Civic EP", "Civic FN", "Civic FK", "Civic X",
            "Civic XI", "Accord", "Accord VI", "Accord VII", "Accord VIII", "Accord IX",
            "Jazz", "Jazz II", "Jazz III", "CR-V", "CR-V III", "CR-V IV", "CR-V V",
            "HR-V", "HR-V II", "CR-Z", "Prelude", "Prelude 4", "NSX", "S2000",
            "Insight", "Insight II", "FR-V", "Stream", "Legend", "Integra", "Fit",
            "Element", "Pilot", "Civic Type R", "Honda e", "ZR-V", "CRX"],
    "Nissan": ["Micra", "Micra K11", "Micra K12", "Micra K13", "Micra K14", "Almera",
            "Almera N15", "Almera N16", "Primera", "Primera P11", "Primera P12",
            "Qashqai", "Qashqai J10", "Qashqai J11", "Qashqai J12", "Juke", "Juke F15",
            "X-Trail", "X-Trail T30", "X-Trail T31", "X-Trail T32", "Note", "Note E11",
            "Navara", "Navara D40", "Pathfinder", "Patrol", "Patrol Y61", "350Z",
            "370Z", "Leaf", "Leaf ZE0", "GT-R", "Skyline", "Sentra", "Sunny",
            "Terrano", "Terrano II", "Cherry", "Pixo", "Cube", "Murano", "Qashqai+2",
            "Pulsar", "Ariya", "Townstar", "Interstar", "NV200"],
    "Mazda": ["2", "2 DE", "2 DJ", "2 DI", "3", "3 BK", "3 BL", "3 BM", "3 BP",
            "323", "323F", "5", "6", "6 GG", "6 GH", "6 GJ", "6 GL", "MX-5",
            "MX-5 NA", "MX-5 NB", "MX-5 NC", "MX-5 ND", "CX-3", "CX-5", "CX-7",
            "CX-9", "CX-30", "CX-60", "CX-80", "MX-30", "RX-7", "RX-8", "626",
            "BT-50", "Premacy", "MPV", "Tribute", "Xedos 6", "Xedos 9", "121",
            "Demio", "MazdaSpeed3", "Bongo"],
    "Mitsubishi": ["Mirage", "Lancer", "Lancer IX", "Lancer X", "Colt", "Colt III",
            "Colt IV", "Colt V", "Galant", "Outlander", "Outlander II", "Outlander III",
            "ASX", "Pajero", "Pajero II", "Pajero III", "Pajero IV", "Shogun",
            "L200", "L200 IV", "Evo", "EVO IV", "EVO X", "Carisma", "Space Star",
            "Eclipse", "Space Runner", "Space Wagon", "Delica", "Grandis", "L300",
            "L400", "Starion", "3000GT", "FTO", "Pajero Pinin"],
    "Suzuki": ["Swift", "Swift V", "Swift VI", "Swift VII", "Ignis", "Vitara", "Vitara II",
            "Vitara III", "Vitara IV", "SX4", "Jimny", "Jimny III", "Jimny IV",
            "Alto", "Alto II", "Grand Vitara", "Baleno", "Celerio", "Kizashi",
            "Wagon R+", "Liana", "Samurai", "SJ413", "SJ410", "Forex", "APV",
            "Splash", "Across", "Aria", "Swift Sport"],
    "Subaru": ["Impreza", "Impreza GC", "Impreza GD", "Impreza GE", "Impreza G4", "WRX",
            "WRX STi", "Legacy", "Legacy IV", "Outback", "Outback III", "Outback V",
            "Forester", "Forester SH", "Forester SJ", "XV", "Crosstrek", "Levorg",
            "BRZ", "Justy", "Tribeca", "Ascent", "Impreza GT", "SVX", "Baja",
            "Solterra", "Leone"],
    "Kia": ["Picanto", "Picanto I", "Picanto II", "Picanto III", "Rio", "Rio III",
            "Rio IV", "Ceed", "Ceed JD", "Ceed CD", "ProCeed", "Cerato", "Cerato III",
            "Sportage", "Sportage I", "Sportage II", "Sportage III", "Sportage IV",
            "Sportage V", "Soul", "Stinger", "Sorento", "Sorento I", "Sorento II",
            "Sorento III", "Optima", "Optima III", "Venga", "Niro", "Niro II",
            "EV6", "EV3", "EV9", "Stonic", "Xceed", "Carens", "Carnival", "Magentis",
            "Clarus", "Sephia", "Pride", "Pregio"],
    "Hyundai": ["i10", "i10 II", "i20", "i20 I", "i20 II", "i20 III", "i30", "i30 I",
            "i30 II", "i30 III", "i40", "Accent", "Accent III", "Elantra", "Elantra IV",
            "Getz", "Santa Fe", "Santa Fe II", "Santa Fe III", "Santa Fe IV",
            "Tucson", "Tucson II", "Tucson III", "Tucson IV", "ix35", "Kona",
            "Kona II", "Veloster", "Ioniq", "Ioniq 5", "Ioniq 6", "Genesis",
            "Coupe", "Lantra", "Sonata", "Sonata IV", "Atos", "Matrix", "Trajet",
            "H1", "H350", "Terracan", "Galloper", "Pony", "Excel", "S-Coupe",
            "iMax", "i800", "Staria", "Bayon", "Santa Cruz"],
    "Dacia": ["Logan", "Logan I", "Logan II", "Sandero", "Sandero I", "Sandero II",
            "Sandero III", "Duster", "Duster I", "Duster II", "Duster III", "Dokker",
            "Lodgy", "Jogger", "Spring", "Nova", "Solenza", "SuperNova", "1300",
            "1410", "1310"],
    "Lada": ["Niva", "Niva Legend", "2101", "2103", "2105", "2106", "2107", "Samara",
             "2108", "2109", "2110", "2111", "2112", "2113", "2114", "2115", "Vesta",
             "Granta", "Kalina", "Priora", "XRAY", "Largus", "1111",
             "Niva Travel"],
    "Mini": ["One", "Cooper", "Cooper S", "John Cooper Works", "Clubman", "Clubman R55",
            "Countryman", "Countryman R60", "Countryman F60", "Paceman", "Roadster",
            "Coupe", "Cabrio", "Mini R50", "Mini R53", "Mini R56", "Mini F56",
            "Mini R57", "Aceman", "Cooper SE"],
    "Smart": ["Fortwo", "Fortwo 450", "Fortwo 451", "Fortwo 453", "Forfour", "Forfour II",
            "Roadster", "EQ fortwo", "EQ forfour", "Crossblade"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck",
             "Model 2"],
    "Porsche": ["911", "911 964", "911 993", "911 996", "911 997", "911 991", "911 992",
            "Boxster", "Boxster 986", "Boxster 987", "Boxster 981", "Boxster 718",
            "Cayman", "Cayman 987", "Cayman 981", "Cayman 718", "Cayenne",
            "Cayenne I", "Cayenne II", "Cayenne III", "Macan", "Panamera",
            "Panamera I", "Panamera II", "924", "928", "944", "968", "356",
            "914", "Taycan", "Taycan Cross Turismo", "918 Spyder", "Carrera GT"],
    "Jaguar": ["XF", "XF X250", "XF X260", "XJ", "XJ X350", "XJ X351", "XE", "XK",
            "XK X100", "XK X150", "F-Type", "F-Pace", "E-Pace", "I-Pace", "S-Type",
            "X-Type", "Mark II", "E-Type", "D-Type", "XJ6", "XJ12", "XJ40",
            "X300", "X308", "XK8", "XJS", "C-Type", "Soverign"],
    "Land Rover": ["Defender", "Defender 90", "Defender 110", "Defender II",
            "Discovery", "Discovery I", "Discovery II", "Discovery III", "Discovery IV",
            "Discovery V", "Discovery Sport", "Freelander", "Freelander I",
            "Freelander II", "Range Rover", "Range Rover Classic", "Range Rover P38",
            "Range Rover L322", "Range Rover L405", "Range Rover Sport",
            "Range Rover Sport L320", "Range Rover Evoque", "Range Rover Velar",
            "Range Rover +", "Series I", "Series II", "Series III"],
    "Lexus": ["IS", "IS 200", "IS 300", "IS II", "IS III", "IS F", "ES", "ES 300",
            "GS", "GS 300", "GS 430", "GS II", "GS III", "LS", "LS 400", "LS 430",
            "LS 460", "RX", "RX 300", "RX 400h", "RX II", "RX III", "RX IV",
            "NX", "UX", "RC", "LC", "LX", "GX", "CT", "SC", "LFA", "RZ", "LBX",
            "SC 430"],
    "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX60", "QX70", "EX",
            "EX35", "FX", "FX35", "FX37", "G", "G37", "M", "M37", "G35", "G25"],
    "Chrysler": ["300C", "300C (2005)", "300C (2011)", "Voyager", "Grand Voyager",
            "PT Cruiser", "Neon", "Sebring", "Crossfire", "Concorde", "Vision",
            "Stratus", "Grand Cherokee", "LeBaron", "New Yorker", "Pacifica",
            "300", "Aspen"],
    "Dodge": ["Charger", "Challenger", "Durango", "Grand Caravan", "Journey", "Caliber",
            "Viper", "Avenger", "Dart", "Nitro", "Magnum", "Ram 1500", "Neon",
            "Intrepid", "Stratus"],
    "Jeep": ["Wrangler", "Wrangler TJ", "Wrangler JK", "Wrangler JL", "Grand Cherokee",
            "Grand Cherokee II", "Grand Cherokee III", "Grand Cherokee IV",
            "Grand Cherokee V", "Cherokee", "Cherokee XJ", "Cherokee KJ",
            "Cherokee KL", "Compass", "Compass II", "Renegade", "Gladiator",
            "Liberty", "Commander", "Patriot", "Wagoneer", "Avenger", "Grand Cherokee L"],
    "MG": ["ZS", "ZS (2017)", "HS", "Marvel R", "MG3", "MG4", "MG5", "MG Flying",
            "MG TF", "MG ZR", "MG ZT", "MG F", "MGB", "Midget", "MG6", "Cyberster",
            "Rover 25", "Rover 45", "Rover 75"],
    "Polestar": ["Polestar 1", "Polestar 2", "Polestar 3", "Polestar 4"],
    "Cupra": ["Leon", "Leon (2020)", "Ateca", "Formentor", "Born", "Tavascan", "Terramar"],
    "Alpine": ["A110", "A110s", "A310", "A610", "A290", "A290_GT"],
    "DS Automobiles": ["DS3", "DS4", "DS7", "DS7 Crossback", "DS9", "DS 3",
            "DS 4 (2022)", "DS5LS"],
    "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80", "G70 Shooting Brake"],
    "Chevrolet": ["Spark", "Spark II", "Aveo", "Cruze", "Camaro", "Corvette",
            "Volt", "Malibu", "Captiva", "Trax", "Orlando", "Epica", "Nubira",
            "Lacetti", "Kalos", "Matiz", "Evanda", "Cavalier", "Tacuma"],
    "Lotus": ["Elise", "Elise S1", "Exige", "Evora", "Esprit", "Emira", "Eletre",
            "Evija", "Elan", "Elite", "Excel", "Europa", "Seven", "Exige S"],
    "Aston Martin": ["DB5", "DB6", "DB7", "DB9", "DB11", "DBS", "DBS Superleggera",
            "Vantage", "V8 Vantage", "Vanquish", "Valkyrie", "DBX", "Rapide",
            "Cygnet", "DB2", "DB4", "DB5", "DB6", "V12 Vantage"],
    "Bentley": ["Continental GT", "Continental Flying Spur", "Flying Spur",
            "Bentayga", "Mulsanne", "Azure", "Arnage", "Brooklands", "Eight",
            "Continental R", "Turbo R", "Continental GTC", "Blower", "Bentayga S"],
    "Rolls-Royce": ["Phantom", "Phantom VII", "Phantom VIII", "Ghost", "Ghost II",
            "Wraith", "Dawn", "Cullinan", "Silver Shadow", "Silver Spirit",
            "Silver Spur", "Spectre", "Corniche", "Park Ward"],
    "Maserati": ["Ghibli", "Ghibli III", "GranTurismo", "Quattroporte", "LeVante",
            "Levante", "GranCabrio", "MC20", "Grecale", "3200 GT", "Spyder",
            "Coupe", "Biturbo", "Shamal", "GT", "Bora", "Mistral", "346",
            "Folgore"],
    "Ferrari": ["F8 Tributo", "488", "488 GTB", "812 Superfast", "Roma", "Portofino",
            "SF90 Stradale", "296 GTB", "F40", "F50", "Enzo", "LaFerrari",
            "Testarossa", "458", "458 Italia", "California", "California T",
            "GTC4Lusso", "FF", "F12", "599", "612", "575M", "550", "456",
            "512 TR", "512M", "348", "328", "308", "F355", "360", "430",
            "296 GTS", "Purosangue"],
    "Lamborghini": ["Huracan", "Aventador", "Gallardo", "Murcielago", "Diablo",
            "Countach", "Urus", "LM002", "Revuelto", "Tempest", "Miura",
            "Jarama", "Espada", "Silhouette", "Jalpa", "Sian", "Aventador SV",
            "Huracan STO"],
    "McLaren": ["570S", "600LT", "720S", "765LT", "750S", "P1", "Senna", "Artura",
            "GT", "12C", "540C", "570GT", "F1", "650S", "675LT", "Speedtail",
            "Solus GT"],
    "Bugatti": ["Veyron", "Veyron 16.4", "Chiron", "Divo", "La Voiture Noire",
            "EB110", "Centodieci", "Chiron Super Sport", "Mistral", "Bolide",
            "Aerolithe"],
    "Pagani": ["Zonda", "Huayra", "Utopia", "C12", "Zonda C12", "Zonda F", "Cinque",
            "Huayra BC", "Imola", "Zonda Revolucion", "Zonda Fantasma"],
    "Koenigsegg": ["Agera", "Agera RS", "Jesko", "Regera", "Gemera", "CCX",
            "CC8S", "One:1", "CCR", "Agera R", "Jesko Absolut", "CC850"],
    "Ariel": ["Atom", "Atom 2", "Atom 3", "Atom 4", "Nomad"],
    "Caterham": ["Seven", "Super Seven", "21", "620R", "340R", "R500", "Classic Seven",
            "CSR", "Seven 360", "Seven 420"],
    "Morgan": ["Plus 4", "Plus 8", "Plus 6", "3 Wheeler", "Roadster", "Aero 8",
            "Aero Supersport", "4/4", "V6 Speedster", "Plus Four"],
    "TVR": ["Tuscan", "Cerbera", "Griffith", "Sagaris", "Tamora", "Chimaera",
            "Speed 12", "S", "V8S", "350i", "Tuscan S"],
    "Noble": ["M12", "M400", "M600", "M12 GTO", "M12 GTC"],
    "Vauxhall": ["Astra", "Corsa", "Insignia", "Mokka", "Zafira", "Combo", "Vivaro",
            "Meriva", "Antara", "Adam", "Crossland", "Grandland", "Movano",
            "Agila", "Vectra", "Cascada", "Carlton", "Frontera", "Omega", "Monaro"],
    "SsangYong": ["Tivoli", "Korando", "Korando II", "Rexton", "Rexton II", "Rodius",
            "Kyron", "Actyon", "Musso", "Torres", "Chairman", "Korando Turismo",
            "Family"],
    "BYD": ["Atto 3", "Dolphin", "Seal", "Han", "Tang", "Seal U", "Seal U DM-i",
            "Dolphin Mini", "T3", "e6", "e5", "Song Plus", "Yuan Plus"],
    "Xpeng": ["G9", "G6", "P7", "P5", "X9", "mONA M03", "P7+"],
    "NIO": ["ET5", "ET7", "ES8", "EL6", "EL7", "EL8", "ES6", "EC6", "ET5 Touring"],
    "ORA / GWM": ["Funky Cat", "Good Cat", "Lightning Cat", "Ballet Cat", "Cat 03"],
    "Zeekr": ["001", "009", "X", "7X", "MIX"],
    "Seres": ["SF5", "SF5 Sports"],
    "Abarth": ["500", "500 (2008)", "595", "695", "124 Spider", "Punto Evo",
            "Grande Punto", "500X", "Punto"],
    "Daihatsu": ["Cuore", "Sirion", "Terios", "Charade", "Materia", "Trevis",
            "Move", "Applause", "Rocky", "FourTrack"],
    "Rover": ["25", "45", "75", "200", "400", "600", "800", "SD1", "90",
            "Metro", "Mini", "Streetwise", "400 Series", "600 Series"],
    "Isuzu": ["D-Max", "D-Max II", "Rodeo", "Trooper", "Pickup", "Midi", "Hombre",
            "MU", "Aska", "Gemini", "Amigo", "Bighorn"],
    "Hummer": ["H1", "H2", "H3", "H3T"],
    "Trabant": ["601", "P50", "P70", "1.1", "P60"],
    "Wartburg": ["353", "1.3", "311", "312", "353 W"],
    "Moskvitch": ["408", "412", "2140", "2138", "427", "2141", "2715", "412E"],
    "ZAZ": ["965", "966", "968", "1102", "1103", "Slavuta", "Tavria", "Sens", "1105"],
    "Proton": ["Saga", "Persona", "Wira", "Perdana", "Putra", "Satria", "Gen-2"],
    "Great Wall": ["Hover", "Hover H3", "Hover H5", "Voleex", "Cool Bear", "Florid",
            "Wingle", "Steed"],
    "Maxus": ["eDeliver 3", "eDeliver 7", "eV80", "T90 EV", "MIFA 7", "MIFA 9"],
    "Aiways": ["U5", "U6"],
    "Leapmotor": ["T03", "C10", "C11", "C01"],
    "Fisker": ["Ocean", "Ocean One", "Karma", "Pear"],
    "Lynk & Co": ["01", "02", "09", "03", "06"],
    "Omoda": ["Omoda 5", "Omoda E5"],
    "Jaecoo": ["Jaecoo 7"],
}


def main():
    db = SessionLocal()
    try:
        brand_count = 0
        model_count = 0
        variation_count = 0
        for brand, models in CATALOG.items():
            get_or_create_brand(db, brand)
            brand_count += 1
            for model in models:
                get_or_create_vehicle_model(db, brand, model)
                model_count += 1
        for brand, models in VARIATIONS.items():
            for model, variants in models.items():
                get_or_create_vehicle_model(db, brand, model)
                for variant in variants:
                    get_or_create_vehicle_model(db, brand, f"{model} {variant}")
                    variation_count += 1
        print(f"catalog ready: {brand_count} brands, {model_count} model entries, "
              f"{variation_count} engine variations "
              f"(categories checked/created).")
    finally:
        db.close()


if __name__ == "__main__":
    main()